/*
  Usage:
  node ./wc.js file1
  node ./wc.js -l file1
  node ./wc.js -c file1
  node ./wc.js -w file1
  node ./wc.js file1 file2
  node ./wc.js -lw file1 [file2]...
  node ./wc.js -wl file1 [file2]...
  node ./wc.js -cl file1 [file2]...
  node ./wc.js -lc file1 [file2]...
  node ./wc.js -wc file1 [file2]...
  node ./wc.js -cw file1 [file2]...
  node ./wc.js -lcw file1 [file2]...
  node ./wc.js -lwc file1 [file2]...
  node ./wc.js -wcc file1 [file2]...
  node ./wc.js -wlc file1 [file2]...
  node ./wc.js -wlc file1 [file2]...
  node ./wc.js -l -w file1 [file2]...
  node ./wc.js -l -c file1 [file2]...
  node ./wc.js -w -c file1 [file2]...
  node ./wc.js -w -l file1 [file2]...
  node ./wc.js -c -l file1 [file2]...
  node ./wc.js -c -w file1 [file2]...
  node ./wc.js -l -c -w file1 [file2]...
  node ./wc.js -l -w -c file1 [file2]...
  node ./wc.js -w -l -c file1 [file2]...
  node ./wc.js -w -c -l file1 [file2]...
  node ./wc.js -c -w -l file1 [file2]...
  node ./wc.js -c -l -w file1 [file2]...
*/
const { readFileSync } = require("fs");

const main = function () {
  let fileName = process.argv[2];
  let fileContent = readFileSync(fileName, "utf8");
  let lineCount = fileContent.split("\n").length - 1;
  const wordCounter = function (count, line) {
    return count + line.split(" ").length;
  };
  let wordCount = fileContent.split("\n").reduce(wordCounter, 0) - 1;
  let byteCount = fileContent.split("").length;
  console.log("", lineCount, wordCount, byteCount, fileName);
};

main();